//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> NomeEsteso()
    * f1 -> <SEPARATORE>
    * f2 -> ( Opzioni() <SEPARATORE> )*
    * f3 -> ( Sottoricetta() <SEPARATORE> )*
    * f4 -> <_INGREDIENTI>
    * f5 -> ListaIngredienti()
    * f6 -> <SEPARATORE>
    * f7 -> <_PREPARAZIONE>
    * f8 -> Preparazione()
    * f9 -> ( <FINENOTA> | <EOF> )
    * f10 -> ( <FINE> | <EOF> )
    */
   public void visit(Ricetta n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
   }

   /**
    * f0 -> ( <STRING> )+
    */
   public void visit(NomeEsteso n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( <_SALVA> NomeSalvataggio() | <_AUTORE> Autore() | <_CATEGORIA> TipoCategoria() | <_DIFFICOLTA> ValoreDifficolta() | <_TEMPO> Tempo() | <_PRIVATA> Privata() | <_STRUMENTI> ListaStrumenti() | <_FESTIVITA> Festivita() | <_PROMEMORIA> Promemoria() )
    */
   public void visit(Opzioni n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <STRING>
    */
   public void visit(NomeSalvataggio n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <STRING>
    */
   public void visit(Autore n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> CategoriaInf()
    * f1 -> [ "(" CategoriaSup() ")" ]
    */
   public void visit(TipoCategoria n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( <STRING> )+
    */
   public void visit(CategoriaInf n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( <STRING> )+
    */
   public void visit(CategoriaSup n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <NUM>
    */
   public void visit(ValoreDifficolta n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> TempoSup()
    * f1 -> [ [ <STRING> ] TempoInf() ]
    */
   public void visit(Tempo n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Durata()
    * f1 -> UnitaTempo()
    */
   public void visit(TempoSup n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Durata()
    * f1 -> UnitaTempo()
    */
   public void visit(TempoInf n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <NUM>
    */
   public void visit(Durata n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <STRING>
    */
   public void visit(UnitaTempo n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <STRING>
    */
   public void visit(Privata n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> Strumento()
    * f1 -> ( "," Strumento() )*
    */
   public void visit(ListaStrumenti n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ( <STRING> )+
    */
   public void visit(Strumento n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( <STRING> )+
    */
   public void visit(Festivita n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( <STRING> | <NUM> )+
    */
   public void visit(Promemoria n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( <_PREPARA> Ricetta() | <_APRI> Apri() )
    */
   public void visit(Sottoricetta n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> NomeSottoricetta()
    * f1 -> [ "(" AutoreSottoricetta() ")" ]
    */
   public void visit(Apri n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <STRING>
    */
   public void visit(NomeSottoricetta n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <STRING>
    */
   public void visit(AutoreSottoricetta n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> Ingrediente()
    * f1 -> ( "," Ingrediente() )*
    */
   public void visit(ListaIngredienti n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> QuantitaIngrediente() TipoIngrediente()
    *       | TipoIngrediente() [ QuantitaIngrediente() ]
    */
   public void visit(Ingrediente n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( <STRING> )+
    */
   public void visit(TipoIngrediente n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <QUANTITA>
    *       | <NUM>
    */
   public void visit(QuantitaIngrediente n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( Nota() | <_OPENLINK> Link() [ <_STARTDESC> DescrizioneLink() ] <_CLOSELINK> )+
    */
   public void visit(Preparazione n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <NOTA>
    */
   public void visit(Nota n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <ADVSTRING>
    */
   public void visit(Link n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <ADVSTRING>
    */
   public void visit(DescrizioneLink n) {
      n.f0.accept(this);
   }

}
