/* Generated By:JavaCC: Do not edit this line. RicettaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RicettaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEPARATORE = 1;
  /** RegularExpression Id. */
  int FINE = 2;
  /** RegularExpression Id. */
  int NUM = 3;
  /** RegularExpression Id. */
  int STRING = 4;
  /** RegularExpression Id. */
  int QUANTITA = 5;
  /** RegularExpression Id. */
  int _SALVA = 6;
  /** RegularExpression Id. */
  int _AUTORE = 7;
  /** RegularExpression Id. */
  int _CATEGORIA = 8;
  /** RegularExpression Id. */
  int _DIFFICOLTA = 9;
  /** RegularExpression Id. */
  int _TEMPO = 10;
  /** RegularExpression Id. */
  int _PRIVATA = 11;
  /** RegularExpression Id. */
  int _STRUMENTI = 12;
  /** RegularExpression Id. */
  int _FESTIVITA = 13;
  /** RegularExpression Id. */
  int _PROMEMORIA = 14;
  /** RegularExpression Id. */
  int _PREPARA = 15;
  /** RegularExpression Id. */
  int _APRI = 16;
  /** RegularExpression Id. */
  int _INGREDIENTI = 17;
  /** RegularExpression Id. */
  int _PREPARAZIONE = 18;
  /** RegularExpression Id. */
  int NOTA = 21;
  /** RegularExpression Id. */
  int FINENOTA = 22;
  /** RegularExpression Id. */
  int _OPENLINK = 23;
  /** RegularExpression Id. */
  int ADVSTRING = 24;
  /** RegularExpression Id. */
  int _STARTDESC = 25;
  /** RegularExpression Id. */
  int _CLOSELINK = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int StatoPreparazione = 1;
  /** Lexical state. */
  int StatoInserimentoLink = 2;
  /** Lexical state. */
  int StatoCommento = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SEPARATORE>",
    "\"_\"",
    "<NUM>",
    "<STRING>",
    "<QUANTITA>",
    "\"SALVA:\"",
    "\"AUTORE:\"",
    "\"CATEGORIA:\"",
    "<_DIFFICOLTA>",
    "\"TEMPO:\"",
    "\"PRIVATA:\"",
    "<_STRUMENTI>",
    "<_FESTIVITA>",
    "\"PROMEMORIA:\"",
    "\"PREPARA:\"",
    "\"APRI:\"",
    "\"INGREDIENTI:\"",
    "<_PREPARAZIONE>",
    "\" \"",
    "\"\\t\"",
    "<NOTA>",
    "\"_\"",
    "\"[\"",
    "<ADVSTRING>",
    "\";\"",
    "\"]\"",
    "\"(*\"",
    "\"*)\"",
    "<token of kind 29>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
