package parser;
/* Generated By:JavaCC: Do not edit this line. RicettaParserConstants.java */
public interface RicettaParserConstants {

  int EOF = 0;
  int SEPARATORE = 1;
  int FINE = 2;
  int NUM = 3;
  int STRING = 4;
  int QUANTITA = 5;
  int _SALVA = 6;
  int _AUTORE = 7;
  int _CATEGORIA = 8;
  int _DIFFICOLTA = 9;
  int _TEMPO = 10;
  int _PRIVATA = 11;
  int _STRUMENTI = 12;
  int _FESTIVITA = 13;
  int _PROMEMORIA = 14;
  int _PREPARA = 15;
  int _APRI = 16;
  int _INGREDIENTI = 17;
  int _PREPARAZIONE = 18;
  int NOTA = 21;
  int FINENOTA = 22;
  int _OPENLINK = 23;
  int ADVSTRING = 24;
  int _STARTDESC = 25;
  int _CLOSELINK = 26;

  int DEFAULT = 0;
  int StatoPreparazione = 1;
  int StatoInserimentoLink = 2;
  int StatoCommento = 3;

  String[] tokenImage = {
    "<EOF>",
    "<SEPARATORE>",
    "\"_\"",
    "<NUM>",
    "<STRING>",
    "<QUANTITA>",
    "\"SALVA:\"",
    "\"AUTORE:\"",
    "\"CATEGORIA:\"",
    "<_DIFFICOLTA>",
    "\"TEMPO:\"",
    "\"PRIVATA:\"",
    "<_STRUMENTI>",
    "<_FESTIVITA>",
    "\"PROMEMORIA:\"",
    "\"PREPARA:\"",
    "\"APRI:\"",
    "\"INGREDIENTI:\"",
    "<_PREPARAZIONE>",
    "\" \"",
    "\"\\t\"",
    "<NOTA>",
    "\"_\"",
    "\"[\"",
    "<ADVSTRING>",
    "\";\"",
    "\"]\"",
    "\"(*\"",
    "\"*)\"",
    "<token of kind 29>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
