//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( <_SALVA> NomeSalvataggio() | <_AUTORE> Autore() | <_CATEGORIA> TipoCategoria() | <_DIFFICOLTA> ValoreDifficolta() | <_TEMPO> Tempo() | <_PRIVATA> Privata() | <_STRUMENTI> ListaStrumenti() | <_FESTIVITA> Festivita() | <_PROMEMORIA> Promemoria() )
 */
public class Opzioni implements Node {
   public NodeChoice f0;

   public Opzioni(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

