//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> NomeEsteso()
 * f1 -> <SEPARATORE>
 * f2 -> ( Opzioni() <SEPARATORE> )*
 * f3 -> ( Sottoricetta() <SEPARATORE> )*
 * f4 -> <_INGREDIENTI>
 * f5 -> ListaIngredienti()
 * f6 -> <SEPARATORE>
 * f7 -> <_PREPARAZIONE>
 * f8 -> Preparazione()
 * f9 -> ( <FINENOTA> | <EOF> )
 * f10 -> ( <FINE> | <EOF> )
 */
public class Ricetta implements Node {
   public NomeEsteso f0;
   public NodeToken f1;
   public NodeListOptional f2;
   public NodeListOptional f3;
   public NodeToken f4;
   public ListaIngredienti f5;
   public NodeToken f6;
   public NodeToken f7;
   public Preparazione f8;
   public NodeChoice f9;
   public NodeChoice f10;

   public Ricetta(NomeEsteso n0, NodeToken n1, NodeListOptional n2, NodeListOptional n3, NodeToken n4, ListaIngredienti n5, NodeToken n6, NodeToken n7, Preparazione n8, NodeChoice n9, NodeChoice n10) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
      f9 = n9;
      f10 = n10;
   }

   public Ricetta(NomeEsteso n0, NodeToken n1, NodeListOptional n2, NodeListOptional n3, ListaIngredienti n4, NodeToken n5, NodeToken n6, Preparazione n7, NodeChoice n8, NodeChoice n9) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = new NodeToken("INGREDIENTI:");
      f5 = n4;
      f6 = n5;
      f7 = n6;
      f8 = n7;
      f9 = n8;
      f10 = n9;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

